# Generated by Django 2.1.3 on 2019-01-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MboardType',
            field=models.CharField(choices=[('sell', '팝니다'), ('buy', '삽니다')], default='Lost', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='MitemType',
            field=models.CharField(choices=[('book', '책'), ('cloth', '옷'), ('electronics', '전자기기'), ('lifeItems', '생활용품'), ('house', '집'), ('job', '구인구직'), ('cosmetics', '화장품'), ('etc', '기타')], default='idcard', max_length=10),
        ),
    ]
