# Generated by Django 2.1.3 on 2019-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_auto_20190125_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=20, null=True, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=20, null=True, verbose_name='작성자'),
        ),
    ]
