# Generated by Django 2.1.3 on 2019-01-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_auto_20190128_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='RWboardType',
            field=models.CharField(blank=True, choices=[('Argument', '찬반토론'), ('General', '일반토론')], max_length=10),
        ),
    ]
