# Generated by Django 2.1.3 on 2019-01-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0004_post_rwboardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='RWboardType',
            field=models.CharField(choices=[('Argument', '찬반토론'), ('General', '일반토론')], default='찬반토론', max_length=10),
        ),
    ]
