# Generated by Django 2.1.3 on 2019-01-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_auto_20190131_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='belongToComment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
