# Generated by Django 2.1.3 on 2019-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0006_auto_20190131_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
