# Generated by Django 2.2.dev20181227094837 on 2019-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_auto_20190129_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentEditor',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
