# Generated by Django 2.1.3 on 2019-02-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_auto_20190131_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentEditor',
        ),
    ]
