# Generated by Django 2.1.5 on 2019-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0010_auto_20190205_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='comrelation',
            name='isReporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postrelation',
            name='isReporter',
            field=models.BooleanField(default=False),
        ),
    ]
