# Generated by Django 2.1.5 on 2019-02-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0012_auto_20190206_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reportResult',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reportResult',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
    ]
