# Generated by Django 2.1.5 on 2019-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0013_auto_20190206_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
