# Generated by Django 2.1.5 on 2019-02-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0014_comment_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new',
        ),
    ]
