# Generated by Django 2.1.5 on 2019-02-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0015_remove_comment_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reportResult',
            field=models.TextField(blank=True, max_length=500, verbose_name='reportResult'),
        ),
    ]
