# Generated by Django 2.1.5 on 2019-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0017_auto_20190211_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
